version: "3.9"

services:
  app:
    container_name: spendings_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app

  db:
    image: postgres:17.2-alpine3.20
    container_name: spendings_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - app-network

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    container_name: spendings_grafana
    ports:
      - "3003:3000"
    env_file:
      - ./grafana/.env
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
