apiVersion: 1
datasources:
  - name: db
    type: postgres
    access: proxy
    url: spendings_db:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    database: ${POSTGRES_DB}
    isDefault: true
    editable: true
    jsonData:
      sslmode: "disable"
